name: zet-cmder
version: "0.1"
author: Patrik Lindstrom. <patrik.lindstrom.dev>
about: Extracts data from several textfile with set based logic
args:
    - FILES:
        short: f
        long: files
        takes_value: true
        multiple: true
        min_values: 1
        about: all files that should be used with set operators  
    - config:
        short: c
        long: config
        value_name: CONF
        help: Sets a custom config file
        takes_value: true
    - OUTPUT:
        short: o
        long: output
        about: Sets the output file to for the result
        required: false
        takes_value: true
    - verbose:
        short: v
        multiple: true
        help: Sets the level of verbosity
subcommands:
    - union:
        about: union set operator between files, all unique rows for all files
        version: "0.1"
        author: Patrik Lindstrom. <patrik.lindstrom.dev>
    - intersect:
        about: intersect set operator between files, what is commont in all files
        version: "0.1"
        author: Patrik Lindstrom. <patrik.lindstrom.dev>        

