name: zet-cmder
version: "0.1"
author: Patrik Lindstrom. <patrik.lindstrom.dev>
about: Extracts data from several textfile with set based logic
args:
    - FILES:
        short: f
        long: files
        takes_value: true
        multiple: true
        min_values: 1
    - config:
        short: c
        long: config
        value_name: CONF
        help: Sets a custom config file
        takes_value: true
    - OUTPUT:
        short: o
        long: output
        required: false
        takes_value: true
    - verbose:
        short: v
        multiple: true
        help: Sets the level of verbosity
    - UNION:
        short: u
        long: union
        takes_value: false
        help: Takes the unique rows of two or more files.
    - INTERSECT:
        short: i
        long: intersection
        takes_value: false
        help: Gets the rows that exist in all of the files.
